/**
 * WhimseyEditor - Modal component for creating and editing whimsies (custom puzzle pieces)
 */

import m from 'mithril';
import type { PathCommand, CustomPiece } from '../geometry/types';
import { PathEditor } from './PathEditor';
import { validateCustomPiece, isPathClosed, type ValidationResult } from '../utils/pathValidation';
import { parseSVGFile, fitPathToCanvas } from './PathEditor/svgParser';
import type MithrilViewEvent from '../utils/MithrilViewEvent';

// Web Awesome components
import '@awesome.me/webawesome/dist/components/dialog/dialog.js';
import '@awesome.me/webawesome/dist/components/button/button.js';
import '@awesome.me/webawesome/dist/components/input/input.js';
import type WaInput from '@awesome.me/webawesome/dist/components/input/input.js';
import '@awesome.me/webawesome/dist/components/icon/icon.js';

// include our CSS
import './WhimseyEditor.css';

/* ========================================================= *\
 *  Component Interface                                      *
\* ========================================================= */

/**
 * Attributes for the WhimseyEditor component.
 */
export interface WhimseyEditorAttrs extends m.Attributes {
  /**
   * Whether the editor dialog is currently open.
   */
  open: boolean;

  /**
   * Optional existing custom piece to edit.
   * If undefined, creates a new custom piece.
   */
  piece?: CustomPiece;

  /**
   * Width of the PathEditor canvas in pixels.
   * Default: 600
   */
  editorWidth?: number;

  /**
   * Height of the PathEditor canvas in pixels.
   * Default: 600
   */
  editorHeight?: number;

  /**
   * Callback invoked when the user saves a custom piece.
   * For new pieces, the id and created timestamp should be generated by the caller.
   *
   * @param piece - The saved custom piece (may be partial for caller to complete)
   */
  onSave: (path: PathCommand[], name?: string) => void;

  /**
   * Callback invoked when the user cancels editing.
   */
  onCancel: () => void;
}

/* ========================================================= *\
 *  Component State                                          *
\* ========================================================= */

interface WhimseyEditorState {
  /** Initial path passed to PathEditor (only set on dialog open) */
  initialPath: PathCommand[];
  /** Current path being edited (for validation) */
  path: PathCommand[];
  /** Current piece name */
  name: string;
  /** Current validation result */
  validation: ValidationResult;
  /** Whether SVG import dialog is open */
  importDialogOpen: boolean;
  /** Track previous open state to detect transitions */
  wasOpen: boolean;
}

/* ========================================================= *\
 *  Component Implementation                                 *
\* ========================================================= */

/**
 * WhimseyEditor - A modal dialog for creating/editing custom pieces
 */
export const WhimseyEditor: m.ClosureComponent<WhimseyEditorAttrs> = () => {
  const state: WhimseyEditorState = {
    initialPath: [],
    path: [],
    name: '',
    validation: { isValid: false, errors: [] },
    importDialogOpen: false,
    wasOpen: false,
  };

  // Reference to the file input element
  let fileInputRef: HTMLInputElement | null = null;

  /**
   * Initialize state from attrs when dialog opens
   */
  const initializeState = (attrs: WhimseyEditorAttrs) => {
    if (attrs.piece) {
      // Editing existing piece
      state.initialPath = attrs.piece.path;
      state.path = attrs.piece.path;
      state.name = attrs.piece.name ?? '';
      // Validate existing piece
      state.validation = validateCustomPiece(state.path);
    } else {
      // Creating new piece - start with empty state
      state.initialPath = [];
      state.path = [];
      state.name = '';
      // Don't show validation errors for empty canvas
      state.validation = { isValid: false, errors: [] };
    }
  };

  /**
   * Handle path changes from PathEditor
   */
  const handlePathChanged = (newPath: PathCommand[]) => {
    state.path = newPath;

    // Only validate if there's a path
    if (newPath.length === 0) {
      state.validation = { isValid: false, errors: [] };
    } else {
      // Always run validation to check if path is closed
      const validationResult = validateCustomPiece(newPath);
      state.validation = validationResult;
    }

    // Don't call m.redraw() here - it triggers a global redraw that can
    // interfere with PuzzleRenderer's Paper.js state. PathEditor already
    // handles its own redraws, and the validation status will update
    // when the user completes the path.
  };

  /**
   * Handle name input changes
   */
  const handleNameChanged = (newName: string) => {
    state.name = newName;
  };

  /**
   * Handle save button click
   */
  const handleSave = (attrs: WhimseyEditorAttrs) => {
    if (!state.validation.isValid) {
      return;
    }
    // Call the onSave callback with path and name
    // The caller is responsible for generating id, transform, and timestamp
    attrs.onSave(state.path, state.name.length > 0 ? state.name : undefined);
  };

  /**
   * Handle SVG file upload
   */
  const handleSVGUpload = (files: FileList | null, editorWidth: number, editorHeight: number) => {
    if (!files || files.length === 0) {
      return;
    }

    const file = files[0];
    if (!file.name.endsWith('.svg')) {
      console.error('Please select an SVG file');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const svgContent = e.target?.result as string;
      if (svgContent) {
        const parseResult = parseSVGFile(svgContent);

        if (parseResult.warning) {
          console.warn('SVG import warning:', parseResult.warning);
        }

        if (parseResult.commands.length > 0) {
          // Fit the path to the canvas size
          const fittedPath = fitPathToCanvas(
            parseResult.commands,
            editorWidth,
            editorHeight
          );

          // Update both initialPath (to reload PathEditor) and path (for validation)
          state.initialPath = fittedPath;
          handlePathChanged(fittedPath);

          // If the file name doesn't have a name yet, use the file name
          if (!state.name) {
            const nameWithoutExtension = file.name.replace(/\.svg$/i, '');
            handleNameChanged(nameWithoutExtension);
          }
        } else {
          console.error('Failed to parse SVG file');
        }
      }
    };
    reader.readAsText(file);
  };

  return {
    oncreate: ({ attrs }) => {
      if (attrs.open) {
        initializeState(attrs);
        state.wasOpen = true;
      }
    },

    onupdate: ({ attrs }) => {
      // Detect dialog opening (transition from closed to open)
      if (attrs.open && !state.wasOpen) {
        initializeState(attrs);
        state.wasOpen = true;
      } else if (!attrs.open && state.wasOpen) {
        // Dialog closed
        state.wasOpen = false;
      }
    },

    view: ({ attrs }) => {
      const editorWidth = attrs.editorWidth ?? 600;
      const editorHeight = attrs.editorHeight ?? 600;

      return m('wa-dialog.custom-piece-editor', {
        open: attrs.open,
        label: attrs.piece ? 'Edit Whimsey' : 'Create Whimsey',
        'onwa-request-close': (e: CustomEvent & MithrilViewEvent) => {
          e.redraw = false;
          attrs.onCancel();
        },
      }, [
        // Dialog content
        m('.editor-content', [
          // Name input
          m('.name-field', [
            m('wa-input', {
              label: 'Piece Name (optional)',
              type: 'text',
              size: 'small',
              value: state.name,
              placeholder: 'Enter a name for this piece',
              onchange: (e: Event & MithrilViewEvent) => {
                e.redraw = false;
                const input = e.target as WaInput;
                handleNameChanged(input.value ?? '');
              },
            }),
          ]),

          // Validation status
          // Show valid message only when path is closed and valid
          // Show error messages whenever there's a path with validation errors
          state.path.length > 0 && (
            state.validation.isValid
              ? (isPathClosed(state.path) && m('.validation-status', [
                m('.valid', [
                  m('wa-icon', {
                    library: 'material',
                    name: 'check_circle',
                    style: 'color: green;',
                  }),
                  m('span', 'Valid whimsey'),
                ]),
              ]))
              : (state.validation.errors.length > 0 && m('.validation-status', [
                m('.invalid', [
                  m('wa-icon', {
                    library: 'material',
                    name: 'error',
                    style: 'color: red;',
                  }),
                  m('span', state.validation.errors.join(', ')),
                ]),
              ]))
          ),

          // PathEditor
          m('.editor-canvas', [
            m(PathEditor, {
              initialPath: state.initialPath,
              onPathChanged: handlePathChanged,
              width: editorWidth,
              height: editorHeight,
              strokeColor: state.validation.isValid ? '#2196F3' : '#f44336',
            }),
          ]),

          // SVG Import button
          m('.import-controls', [
            m('input', {
              type: 'file',
              accept: '.svg',
              style: 'display: none;',
              oncreate: (vnode: m.VnodeDOM) => {
                fileInputRef = vnode.dom as HTMLInputElement;
              },
              onchange: (e: Event & MithrilViewEvent) => {
                e.redraw = false;
                const input = e.target as HTMLInputElement;
                handleSVGUpload(input.files, editorWidth, editorHeight);
                // Reset the input so the same file can be selected again
                input.value = '';
              },
            }),
            m('wa-button', {
              variant: 'default',
              size: 'small',
              onclick: (e: Event & MithrilViewEvent) => {
                e.redraw = false;
                fileInputRef?.click();
              },
            }, 'Import SVG'),
          ]),
        ]),

        // Dialog footer with action buttons
        m('div', {
          slot: 'footer',
          style: 'display: flex; gap: 8px; justify-content: flex-end;',
        }, [
          m('wa-button', {
            variant: 'default',
            onclick: (e: Event & MithrilViewEvent) => {
              e.redraw = false;
              attrs.onCancel();
            },
          }, 'Cancel'),
          m('wa-button', {
            variant: 'primary',
            disabled: !state.validation.isValid,
            onclick: (e: Event & MithrilViewEvent) => {
              e.redraw = false;
              handleSave(attrs);
            },
          }, 'Save'),
        ]),
      ]);
    },
  };
};

export default WhimseyEditor;
